### ISSUE TITLE
error[E0432]: unresolved import `rustc_borrowck::consumers::get_body_with_borrowck_facts`

### ISSUE THREAD

**Issue by Guelakais** [cordx56/rustowl#492]
### Bug Description

while compiling, the following happened:

```sh
error: Cannot build '/nix/store/wnn3rz4vxdmv78nsz4yzxa3xzs2rz2n5-rustowl-1.0.0-rc.1.drv'.
       Reason: builder failed with exit code 101.
       Output paths:
         /nix/store/cs0rlj0hd6c42zbhhyfpxzif1889dpi5-rustowl-1.0.0-rc.1
       Last 25 log lines:
       >    Compiling auto_impl v1.3.0
       >    Compiling hyper-util v0.1.16
       >    Compiling lsp-types v0.94.1
       >    Compiling tower-lsp-macros v0.9.0
       >    Compiling tikv-jemallocator v0.6.0
       >    Compiling cargo_metadata v0.21.0
       >    Compiling pin-project v1.1.10
       >    Compiling tower v0.4.13
       >    Compiling rustls-webpki v0.103.4
       >    Compiling tower-lsp v0.20.0
       >    Compiling tokio-rustls v0.26.2
       >    Compiling hyper-rustls v0.27.7
       >    Compiling reqwest v0.12.23
       > error[E0432]: unresolved import `rustc_borrowck::consumers::get_body_with_borrowck_facts`
       >  --> src/bin/core/analyze.rs:8:5
       >   |
       > 8 |     get_body_with_borrowck_facts,
       >   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       >   |     |
       >   |     no `get_body_with_borrowck_facts` in `consumers`
       >   |     help: a similar name exists in the module: `get_bodies_with_borrowck_facts`
       >
       > For more information about this error, try `rustc --explain E0432`.
       > error: could not compile `rustowl` (bin "rustowlc") due to 1 previous error
```
how to solve it?

### Environment

Nixos-unstable
rustc-version: rustc 1.91.1 (ed61e7d7e 2025-11-07) (built from a source tarball)
`rustup --version`: rustup 1.28.2 (1980-01-01)

**Comment by MuntasirSZN** [comment]
As in main branch, `scripts/build/channel` file is capped in 1.89.0 rust. So it won't compile with 1.91.1. Use rust 1.89.0 and it is guaranteed to compile.

**Comment by Guelakais** [comment]
> As in main branch, `scripts/build/channel` file is capped in 1.89.0 rust. So it won't compile with 1.91.1. Use rust 1.89.0 and it is guaranteed to compile.

When will the software be uncapped? Because I can't modify the version number of my rustc

**Comment by MuntasirSZN** [comment]
@Guelakais See #421

Improtant to note, this pr is unstable, anything can happen. If you want a stable one, you have to wait for v1 which may come this month or later month.

**Comment by MuntasirSZN** [comment]
Also, ummm in that branch rust is 1.92.0 (latest)

**Comment by MuntasirSZN** [comment]
We depend on rustc internals which are unstable, which is why this is capped.

**Comment by cordx56** [comment]
We can support both versions of rustc. I will write some code after the #421 is merged.

**Comment by MuntasirSZN** [comment]
> We can support both versions of rustc. I will write some code after the #421 is merged.

Doable, we can maintain all rust version changes, or like last 5 stable releases (with nightly dates) I think [`rustversion`](https://crates.io/crates/rustversion) crate is needed here...
